apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: monitoring
spec:
  ports:
    - name: prometheus
      port: 9090
      targetPort: prom-port
  selector:
    app: prometheus
    env: test

---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: monitoring
spec:
  ports:
    - name: alertmanager
      port: 9093
      targetPort: alert-port
  selector:
    app: alertmanager
    env: test

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alert-service:9093

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage
  labels:
    volume: prom-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    path: /export/prom-storage
    server: 10.1.240.80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alert-storage
  labels:
    volume: alert-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  nfs:
    path: /export/alert-storage
    server: 10.1.240.80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage
  labels:
    app: prometheus
    env: test
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      volume: prom-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-storage
  labels:
    app: prometheus
    env: test
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      volume: alert-storage

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prom-deployment
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: monitoring
      labels:
        app: prometheus
        env: test
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.3.2
          ports:
            - name: prom-port
              containerPort: 9090
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention=365d
            - --web.enable-lifecycle
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
          # env:
          volumeMounts:
            - name: prom-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prom-storage
              mountPath: /prometheus
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /-/healthy
              port: 9090
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /-/ready
              port: 9090
          # initContainers:
      volumes:
        - name: prom-config
          configMap:
            name: prom-config
        - name: prom-storage
          persistentVolumeClaim:
            claimName: prom-storage

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alert-deployment
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      namespace: monitoring
      labels:
        app: alertmanager
        env: test
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.15.1
          ports:
            - name: alert-port
              containerPort: 9093
          # args:
          # env:
          volumeMounts:
            - name: alert-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
            - name: alert-storage
              mountPath: /alertmanager
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /-/healthy
              port: 9093
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /-/ready
              port: 9093
          # initContainers:
      volumes:
        - name: alert-config
          secret:
            secretName: alert-secret
            optional: false
        - name: alert-storage
          persistentVolumeClaim:
            claimName: alert-storage

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prom-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: prom.k800123.firefly.kutc.kansai-u.ac.jp
      http:
        paths:
          - path: /
            backend:
              serviceName: prom-service
              servicePort: 9090
    - host: alert.k800123.firefly.kutc.kansai-u.ac.jp
      http:
        paths:
          - path: /
            backend:
              serviceName: alert-service
              servicePort: 9093
